### ISSUE TITLE
Error encountered on Unexpected keyword argument while using PEFT

### ISSUE THREAD

**Issue by Ananthzeke** [google-research/metricx#3]
@danieldeutsch 
I attempted to finetune the MT5 Regression model with  shifting the model to peft. Below are my configurations:
```python
  model = models.MT5ForRegression.from_pretrained(args.model_name_or_path,  load_in_4bit=True, device_map="auto")
 config = LoraConfig(
          r=8,
          lora_alpha=2,
          target_modules=["q","v"],
          lora_dropout=0.5,
          bias="none",
          task_type='SEQ_2_SEQ_LM',
      )
  model = get_peft_model(model, config)
```
However I get a TypeError saying it got an unexpected argument 'decoder_input_ids' while trying to finetune the model
```
0%|          | 0/1249 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/.conda/envs/metricx/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/.conda/envs/metricx/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/metricx/metricx23/fine_tune.py", line 276, in <module>
    main()
  File "/data/metricx/metricx23/fine_tune.py", line 261, in main
    trainer.train()
  File "/home/.conda/envs/metricx/lib/python3.9/site-packages/transformers/trainer.py", line 1859, in train
    return inner_training_loop(
  File "/home/.conda/envs/metricx/lib/python3.9/site-packages/transformers/trainer.py", line 2203, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/.conda/envs/metricx/lib/python3.9/site-packages/transformers/trainer.py", line 3138, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/.conda/envs/metricx/lib/python3.9/site-packages/transformers/trainer.py", line 3161, in compute_loss
    outputs = model(**inputs)
  File "/home/.conda/envs/metricx/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/.conda/envs/metricx/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/.conda/envs/metricx/lib/python3.9/site-packages/accelerate/utils/operations.py", line 825, in forward
    return model_forward(*args, **kwargs)
  File "/home/.conda/envs/metricx/lib/python3.9/site-packages/accelerate/utils/operations.py", line 813, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/.conda/envs/metricx/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/.conda/envs/metricx/lib/python3.9/site-packages/peft/peft_model.py", line 1326, in forward
    return self.base_model(
  File "/home/.conda/envs/metricx/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/.conda/envs/metricx/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/.conda/envs/metricx/lib/python3.9/site-packages/peft/tuners/tuners_utils.py", line 161, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/.conda/envs/metricx/lib/python3.9/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'decoder_input_ids'
```

**Comment by Ananthzeke** [comment]
Setting `task_type=None `in the config resolved the issue 
```python
 config = LoraConfig(
          r=8,
          lora_alpha=2,
          target_modules=["q","v"],
          lora_dropout=0.5,
          bias="none",
          task_type=None,
      )
```
